#!/bin/bash

#install opencv from source
sudo apt-get update
sudo apt-get upgrade

#OpenCV 3, Python 3, Ubuntu
sudo apt-get install build-essential cmake git pkg-config libjpeg8-dev libtiff5-dev libjasper-dev libpng12-dev libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libgtk2.0-dev libatlas-base-dev gfortran python2.7-dev
