* Working with org-mode
** Working with capture
** I would like to keep my notes in 'notes.org' 
   in the dotfiles directory that is under git.  I tried setting a soft link to that file. Then I added "(setq org-default-notes-file (expand-file-name "~/.notes.org"))" to .spacemacs but capture mode still seems to use a file under ".emacs.d".  Ok, I lied, it seems to be working now with the first task entered in capture mode.
   
   I changed my mind.  Everything include captures is in notes.org which is in it's own folder within dotfiles.  I also set a [[file:~/dotfiles/spacemacs::(setq%20notes-org%20(expand-file-name%20"~/dotfiles/org/notes.org"))][variable]] to this full path and use that variable to configure everything else.  
** Line wrapping looks like it is working
   but the font size appears to be throwing it off, it is cutting off part of the line.  I just reset the font to 24.  The wrapping looks a lot better now. I also put "(setq org-startup-truncated nil)" into .spacemacs.
** Now I need a capture template for browser bookmarks.
   A template for bookmarks capturing has been added to .spacemacs but the file specifed does not get the data. Oddly enough it just worked.
   Here is the [[file:~/dotfiles/spacemacs::(quote%20(("b"%20"bookmark"%20entry%20(file%20(expand-file-name%20"~/.org/refile.org"))][bookmarks template.]]
*** Now I want to refile the bookmar but I get
** Easy Templates
   http://orgmode.org/manual/Easy-templates.html#Easy-templates
** Funny formating for notes.                                          :NOTE:
 [2017-07-12 Wed 22:29]
 [[file:~/dotfiles/org/notes.org::*Software%20Development][Software Development]]
 
* Working with Spacemacs
** How to make spacemacs split window right automatically?
   https://github.com/syl20bnr/spacemacs/issues/5140
   You can change the values of split-height-threshold and split-width-threshold. These variables decide when and how split-window-sensibly creates a new window. By default, display-buffer uses split-window-sensibly when it needs to create a new window.

   This is really frustrating.  I have set both variables in such as to force either verticle or horizontal splits but the default behavior is unchanged.  One thing that is peculiar is that Spacemacs was spliting windows vertically by default when I first started it.  Could the split behavior be effected by the font size?

   I had the font set to 22 so I could read the screen from a distance. I changed it 13 and got the same results when reading documention on the variables.  Then I changed it 18 and got a right window when I looked at a larger help file. Running an apropos on the variable splits horizontally while following links splits vertically.
* Software Development 
** Working with JavaScript
*** Installing the Spacemacs JavaScript layer
     sudo -H npm install -g tern
     ...
     /usr/local/bin/tern -> /usr/local/lib/node_modules/tern/bin/tern
     /usr/local/lib
     └── tern@0.21.0 

      npm install -g js-beautify
      ...
      /home/kivy/.nvm/versions/node/v6.11.0/bin/css-beautify -> /home/kivy/.nvm/versions/node/v6.11.0/lib/node_modules/js-beautify/js/bin/css-beautify.js
      /home/kivy/.nvm/versions/node/v6.11.0/bin/html-beautify -> /home/kivy/.nvm/versions/node/v6.11.0/lib/node_modules/js-beautify/js/bin/html-beautify.js
      /home/kivy/.nvm/versions/node/v6.11.0/bin/js-beautify -> /home/kivy/.nvm/versions/node/v6.11.0/lib/node_modules/js-beautify/js/bin/js-beautify.js
      /home/kivy/.nvm/versions/node/v6.11.0/lib
└─┬ js-beautify@1.6.14 
  ├─┬ config-chain@1.1.11 
  │ ├── ini@1.3.4 
  │ └── proto-list@1.2.4 
  ├─┬ editorconfig@0.13.2 
  │ ├── bluebird@3.5.0 
  │ ├── commander@2.11.0 
  │ ├─┬ lru-cache@3.2.0 
  │ │ └── pseudomap@1.0.2 
  │ └── sigmund@1.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  └─┬ nopt@3.0.6 
    └── abbrev@1.1.0

     js-beautify --version
         1.6.14
** working with magit
*** How about an 'auto-commit' mode for selected files like Notes.
** eLisp
*** Display a variables value
    #+BEGIN_SRC emacs-lisp
    (default-value 'org-capture-templates)
    #+END_SRC

    #+RESULTS:
    | b | bookmark | entry | (file (expand-file-name ~/.org/refile.org)) | * BOOKMARK %? |
** Adding browser bookmarks to org-mode
*** Developing spacemacs while keeping new updates from overwriting the new code.
   I am not sure how to develop an existing spacemacs layer.  The git project for spacemacs has been cloned and a feature-bookmars branch has been put under develop.  I suppose I will have to merge in updates and then copy the modified file back into the working distribution.

   A submodule for org-cliplinks has been added under the org-mode layer.

*** How is a elisp file added in from the submodule.
** I wonder if elisp exercisms would be a help
*** https://github.com/caiorss/Emacs-Elisp-Programming
    I thought Spacemacs was broken.  I opened up the elisp org-mode file and kept getting a "void variable" error when running elisp blocks.  The problem is that the src blocks have "ELISP>" prompts in them which are non executable.  Now I am trying figure out how to do a search and replace to get rid of them.  

    I also was using the wrong VIM command for search and replace.  I should have used ":%s//g".
*** https://joelmccracken.github.io/entries/emacs-lisp-for-hackers-next/
    Here is a sample Hello World function.

    #+BEGIN_SRC emacs-lisp
    (defun hello-world ()
      "Hello World")

    (hello-world)
    #+END_SRC

    #+RESULTS:
    : hello

* Browser Bookmarks
  http://www.karl-voit.at/2014/08/10/bookmarks-with-orgmode/
  https://github.com/rexim/org-cliplink
  http://doc.norang.ca/org-mode.html#Capture
* BOOKMARKS
** BOOKMARK A bookmark.
 [2017-07-12 Wed 22:29]
* NOTES
